server:
  port: 9980
spring:
  application:
    name: unicorn-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unicorn?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 47.100.131.2:8848
#      config:
#        # 配置中心地址
#        server-addr: 47.100.131.2:8848
#        # 配置文件格式
#        file-extension: yml
#        # 共享配置
#        shared-configs:
#          - application.${spring.cloud.nacos.config.file-extension}